### ISSUE TITLE
Please share the airtable

### ISSUE THREAD

**Issue by zhensongren** [miratcan/eleman#2]
I just submitted access request. Please approve it. You can also share it via link to anyone.
![image](https://user-images.githubusercontent.com/5067769/120935006-64173980-c6c6-11eb-9290-76304df39709.png)

**Comment by ahmetveburak** [comment]
@miratcan maybe you can add your template to https://www.airtable.com/universe
I haven't tried before but it could be help.

**Comment by miratcan** [comment]
Is this link working? @zhensongren @ahmetveburak 

https://airtable.com/invite/l?inviteId=invcMvLdsMXtKJwql&inviteToken=af79b3f907772b28f5708469fdab1aeabeebb58bec3599a2638829fa9c42981d&utm_source=email

**Comment by ahmetveburak** [comment]
> Is this link working? @zhensongren @ahmetveburak
> 
> https://airtable.com/invite/l?inviteId=invcMvLdsMXtKJwql&inviteToken=af79b3f907772b28f5708469fdab1aeabeebb58bec3599a2638829fa9c42981d&utm_source=email

works for me

**Comment by miratcan** [comment]
Closing then.
